import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import { addInternalNote, addStaffPublicComment, fetchStaffOwners, fetchStaffTicket, updateStaffTicketOwner, updateStaffTicketPriority, updateStaffTicketStatus } from "./api.js";
const statuses = ["New", "Open", "InProgress", "WaitingForRequester", "Resolved", "Closed", "Reopened", "Cancelled"];
const priorities = ["LOW", "MEDIUM", "HIGH", "URGENT"];
export default function StaffTicketDetail({ ticketId, onBack }) {
    const [ticket, setTicket] = useState(null);
    const [owners, setOwners] = useState([]);
    const [state, setState] = useState("loading");
    const [error, setError] = useState("");
    const [comment, setComment] = useState("");
    const [note, setNote] = useState("");
    async function reload() { setTicket(await fetchStaffTicket(ticketId)); }
    useEffect(() => { let mounted = true; setState("loading"); Promise.all([fetchStaffTicket(ticketId), fetchStaffOwners()]).then(([loaded, loadedOwners]) => { if (!mounted)
        return; setTicket(loaded); setOwners(loadedOwners); setState("ready"); }).catch(() => { if (mounted)
        setState("error"); }); return () => { mounted = false; }; }, [ticketId]);
    async function update(action) { setError(""); try {
        await action();
        await reload();
    }
    catch (reason) {
        setError(reason instanceof Error ? reason.message : "Unable to update this Ticket.");
    } }
    async function submitComment(event) { event.preventDefault(); if (!comment.trim())
        return; await update(async () => { await addStaffPublicComment(ticketId, comment.trim()); setComment(""); }); }
    async function submitNote(event) { event.preventDefault(); if (!note.trim())
        return; await update(async () => { await addInternalNote(ticketId, note.trim()); setNote(""); }); }
    if (state === "loading")
        return _jsxs("section", { className: "content-card", children: [_jsx("h2", { children: "Ticket Detail" }), _jsx("p", { role: "status", children: "Loading Ticket Detail..." })] });
    if (state === "error" || !ticket)
        return _jsxs("section", { className: "content-card", children: [_jsx("h2", { children: "Ticket Detail" }), _jsx("p", { role: "alert", className: "text-danger", children: "Unable to load this Ticket. It may not exist or you may not have permission." }), _jsx("button", { className: "btn btn-outline-success", onClick: onBack, children: "Back to Queue" })] });
    return _jsxs("section", { className: "detail-page staff-ticket-detail", "aria-labelledby": "staff-ticket-detail-heading", children: [_jsx("button", { className: "back-link", onClick: onBack, children: "\u2190 Back to Queue" }), _jsxs("div", { className: "content-card", children: [_jsxs("div", { className: "section-heading", children: [_jsxs("div", { children: [_jsx("p", { className: "eyebrow", children: "IT STAFF TICKET" }), _jsx("h2", { id: "staff-ticket-detail-heading", children: ticket.ticketNumber })] }), _jsx("span", { className: "status-badge", children: ticket.currentStatus })] }), _jsxs("dl", { className: "row detail-grid", children: [_jsx("dt", { className: "col-sm-4", children: "Requester" }), _jsxs("dd", { className: "col-sm-8", children: [ticket.requester.name, " (", ticket.requester.email, ")"] }), _jsx("dt", { className: "col-sm-4", children: "Category" }), _jsx("dd", { className: "col-sm-8", children: ticket.category.name }), _jsx("dt", { className: "col-sm-4", children: "Related System" }), _jsx("dd", { className: "col-sm-8", children: ticket.relatedSystem.name }), _jsx("dt", { className: "col-sm-4", children: "Summary" }), _jsx("dd", { className: "col-sm-8", children: ticket.summary }), _jsx("dt", { className: "col-sm-4", children: "Description" }), _jsx("dd", { className: "col-sm-8", style: { whiteSpace: "pre-wrap" }, children: ticket.description })] }), error && _jsx("p", { role: "alert", className: "text-danger", children: error }), _jsxs("div", { className: "staff-edit-panel", children: [_jsx("label", { htmlFor: "staff-owner", children: "Owner" }), _jsxs("select", { id: "staff-owner", className: "form-select", value: ticket.owner?.id ?? "", onChange: (event) => { const id = Number(event.target.value); if (id)
                                    void update(() => updateStaffTicketOwner(ticketId, id)); }, children: [_jsx("option", { value: "", children: "Unassigned" }), owners.map((owner) => _jsxs("option", { value: owner.id, children: [owner.name, " (", owner.role, ")"] }, owner.id))] }), _jsx("label", { htmlFor: "staff-priority", children: "IT Priority" }), _jsx("select", { id: "staff-priority", className: "form-select", value: ticket.itPriority, onChange: (event) => void update(() => updateStaffTicketPriority(ticketId, event.target.value)), children: priorities.map((item) => _jsx("option", { value: item, children: item }, item)) }), _jsx("label", { htmlFor: "staff-ticket-status", children: "Status" }), _jsx("select", { id: "staff-ticket-status", className: "form-select", value: ticket.currentStatus, onChange: (event) => void update(() => updateStaffTicketStatus(ticketId, event.target.value)), children: statuses.map((item) => _jsx("option", { value: item, children: item }, item)) })] }), _jsxs("div", { className: "staff-communication-grid", children: [_jsxs("div", { className: "content-card public-comments-panel", children: [_jsx("h3", { children: "Public Comments" }), _jsx("ul", { children: ticket.publicComments.map((item) => _jsxs("li", { children: [_jsx("strong", { children: item.author.name }), _jsx("small", { children: new Date(item.createdAt).toLocaleString() }), _jsx("p", { children: item.content })] }, item.id)) }), _jsxs("form", { onSubmit: submitComment, children: [_jsx("label", { htmlFor: "staff-public-comment", children: "Add a Public Comment" }), _jsx("textarea", { id: "staff-public-comment", className: "form-control", rows: 3, value: comment, onChange: (event) => setComment(event.target.value), maxLength: 2000 }), _jsx("button", { className: "btn btn-success", type: "submit", disabled: !comment.trim(), children: "Post Public Comment" })] })] }), _jsxs("div", { className: "content-card internal-notes-panel", children: [_jsx("h3", { children: "Internal Notes" }), _jsx("ul", { children: ticket.internalNotes.map((item) => _jsxs("li", { children: [_jsx("strong", { children: item.author.name }), _jsx("small", { children: new Date(item.createdAt).toLocaleString() }), _jsx("p", { children: item.content })] }, item.id)) }), _jsxs("form", { onSubmit: submitNote, children: [_jsx("label", { htmlFor: "staff-internal-note", children: "Add an Internal Note" }), _jsx("textarea", { id: "staff-internal-note", className: "form-control", rows: 3, value: note, onChange: (event) => setNote(event.target.value), maxLength: 2000 }), _jsx("button", { className: "btn btn-outline-success", type: "submit", disabled: !note.trim(), children: "Add Internal Note" })] })] })] })] })] });
}
