import { useEffect, useState } from "react";
import { fetchStaffTickets, StaffTicketListItem, TicketPriority, TicketStatus } from "./api.js";

type Props = { onOpenTicket: (ticketId: number) => void };
const statuses: TicketStatus[] = ["New", "Open", "InProgress", "WaitingForRequester", "Resolved", "Closed", "Reopened", "Cancelled"];
const priorities: TicketPriority[] = ["LOW", "MEDIUM", "HIGH", "URGENT"];

function displayStatus(status: TicketStatus) { return status === "InProgress" ? "In Progress" : status === "WaitingForRequester" ? "Waiting for Requester" : status; }
function priorityClass(priority: TicketPriority) { return `priority-badge priority-${priority.toLowerCase()}`; }
function statusClass(status: TicketStatus) { return `status-badge queue-status-${status.toLowerCase()}`; }

export default function StaffTicketQueue({ onOpenTicket }: Props) {
  const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [priority, setPriority] = useState("");
  const [tickets, setTickets] = useState<StaffTicketListItem[]>([]); const [state, setState] = useState<"loading" | "ready" | "error">("loading"); const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1); const [totalItems, setTotalItems] = useState(0);
  useEffect(() => { let mounted = true; setState("loading"); const params = new URLSearchParams({ page: String(page), pageSize: "10", sortBy: "updatedAt", sortDirection: "desc" }); if (search.trim()) params.set("search", search.trim()); if (status) params.set("status", status); if (priority) params.set("priority", priority); void fetchStaffTickets(params).then((result) => { if (!mounted) return; setTickets(result.data); setTotalItems(result.pagination.totalItems); setTotalPages(result.pagination.totalPages || 1); setState("ready"); }).catch(() => { if (mounted) setState("error"); }); return () => { mounted = false; }; }, [page, priority, search, status]);
  function applySearch(event: React.FormEvent) { event.preventDefault(); setPage(1); }
  const firstResult = totalItems === 0 ? 0 : (page - 1) * 10 + 1; const lastResult = Math.min(page * 10, totalItems);
  return <section className="staff-queue-page" aria-labelledby="staff-queue-heading">
    <div className="staff-queue-title"><div><p className="eyebrow">IT STAFF WORKSPACE</p><h1 id="staff-queue-heading">My Queue</h1></div></div>
    <form className="staff-queue-filters" onSubmit={applySearch}><label className="visually-hidden" htmlFor="staff-search">Search tickets</label><input id="staff-search" className="form-control staff-search-input" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by ticket number or summary..." /><button className="staff-filter-button" type="button" onClick={() => { setStatus(""); setPriority(""); setPage(1); }}>☷ <span>Filters</span></button><div className="staff-filter-selects"><label htmlFor="staff-status">Status</label><select id="staff-status" className="form-select" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="">All statuses</option>{statuses.map((item) => <option key={item} value={item}>{displayStatus(item)}</option>)}</select><label htmlFor="staff-priority">IT Priority</label><select id="staff-priority" className="form-select" value={priority} onChange={(event) => { setPriority(event.target.value); setPage(1); }}><option value="">All priorities</option>{priorities.map((item) => <option key={item} value={item}>{item}</option>)}</select></div><button className="btn btn-success visually-hidden" type="submit">Search</button></form>
    {state === "loading" && <p role="status">Loading Ticket Queue...</p>}
    {state === "error" && <p role="alert" className="text-danger">Unable to load the Ticket Queue. Please try again.</p>}
    {state === "ready" && <p className="staff-result-count">Showing {firstResult} to {lastResult} of {totalItems} tickets</p>}
    {state === "ready" && tickets.length === 0 && <p className="staff-empty-state" role="status">{search || status || priority ? "No Tickets match these filters." : "The Ticket Queue is empty."}</p>}
    {state === "ready" && tickets.length > 0 && <div className="table-responsive staff-queue-table-wrap"><table className="table staff-queue-table"><caption className="visually-hidden">IT Staff Ticket Queue</caption><thead><tr><th>Ticket No. <span aria-hidden="true">↕</span></th><th>Created Date <span aria-hidden="true">↕</span></th><th>Summary</th><th>Category <span aria-hidden="true">↕</span></th><th>Req. Priority</th><th>IT Priority</th><th>Status <span aria-hidden="true">↕</span></th><th>Owner <span aria-hidden="true">↕</span></th></tr></thead><tbody>{tickets.map((ticket) => <tr key={ticket.id}><td><button className="link-button staff-ticket-number" onClick={() => onOpenTicket(ticket.id)}>{ticket.ticketNumber}</button></td><td>{new Date(ticket.ticketDate).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })}</td><td className="staff-summary-cell">{ticket.summary}</td><td>{ticket.category.name}</td><td><span className={priorityClass(ticket.requestedPriority as TicketPriority)}>{ticket.requestedPriority}</span></td><td><span className={priorityClass(ticket.itPriority)}>{ticket.itPriority}</span></td><td><span className={statusClass(ticket.currentStatus)}>{displayStatus(ticket.currentStatus)}</span></td><td>{ticket.owner?.name ?? "Unassigned"}</td></tr>)}</tbody></table></div>}
    {state === "ready" && totalPages > 1 && <nav className="queue-pagination" aria-label="Ticket Queue pagination"><button className="btn btn-outline-success" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>‹ <span>Previous</span></button><div className="queue-page-numbers" aria-label="Pages">{Array.from({ length: totalPages }, (_, index) => index + 1).map((pageNumber) => <button key={pageNumber} type="button" className={pageNumber === page ? "queue-page-number active" : "queue-page-number"} aria-current={pageNumber === page ? "page" : undefined} onClick={() => setPage(pageNumber)}>{pageNumber}</button>)}</div><button className="btn btn-outline-success" disabled={page >= totalPages} onClick={() => setPage((value) => value + 1)}>Next ›</button></nav>}
  </section>;
}
