import { jsx as _jsx } from "react/jsx-runtime";
import { afterEach, describe, expect, it, vi } from "vitest";
import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import App from "../../src/App.js";
import * as api from "../../src/api.js";
import { RequesterProvider } from "../../src/requesterContext.js";
function renderApp() { return render(_jsx(RequesterProvider, { children: _jsx(App, {}) })); }
describe("Lab 2 Create Ticket", () => { afterEach(() => vi.restoreAllMocks()); it("validates required fields and submits valid data", async () => { vi.spyOn(api, "fetchDevelopmentRequesters").mockResolvedValue([{ id: 1, name: "Active User", email: "active@example.com" }]); vi.spyOn(api, "fetchCategories").mockResolvedValue([{ id: 1, name: "Hardware" }]); vi.spyOn(api, "fetchRelatedSystems").mockResolvedValue([{ id: 1, name: "Laptop" }]); const create = vi.spyOn(api, "createTicket").mockResolvedValue({ id: 1, requesterId: 1, categoryId: 1, relatedSystemId: 1, summary: "Laptop issue", requestedPriority: "MEDIUM", description: "The laptop cannot start correctly.", ticketNumber: "TK-2026-000001", ticketDate: "2026-09-01T00:00:00.000Z", currentStatus: "New", createdAt: "2026-09-01T00:00:00.000Z", updatedAt: "2026-09-01T00:00:00.000Z" }); const user = userEvent.setup(); renderApp(); await user.selectOptions(await screen.findByRole("combobox", { name: "Development Requester" }), "1"); await user.click(screen.getByRole("button", { name: "Continue" })); await user.click(screen.getByRole("button", { name: "Create Ticket" })); await user.click(await screen.findByRole("button", { name: "Submit Ticket" })); expect(screen.getByText("Category is required.")).toBeInTheDocument(); await user.selectOptions(screen.getByRole("combobox", { name: "Category *" }), "1"); await user.selectOptions(screen.getByRole("combobox", { name: "Related System *" }), "1"); await user.type(screen.getByRole("textbox", { name: "Summary *" }), "Laptop issue"); await user.selectOptions(screen.getByRole("combobox", { name: "Requested Priority *" }), "MEDIUM"); await user.type(screen.getByRole("textbox", { name: "Description *" }), "The laptop cannot start correctly."); await user.click(screen.getByRole("button", { name: "Submit Ticket" })); expect(await screen.findByText("Ticket created: TK-2026-000001")).toBeInTheDocument(); expect(create).toHaveBeenCalledOnce(); }); });
